<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <NoWarn>1701;1702;1591</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GtMotive.Fleet.ApplicationCore\GtMotive.Fleet.ApplicationCore.csproj" />
        <ProjectReference Include="..\GtMotive.Fleet.Infrastructure\GtMotive.Fleet.Infrastructure.csproj" />
    </ItemGroup>

</Project>
