<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <UserSecretsId>dfa2604e-8bbc-4ef5-8767-d4a5b7247b0d</UserSecretsId>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>1591</NoWarn>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Expressions" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GtMotive.Fleet.Api\GtMotive.Fleet.Api.csproj" />
        <ProjectReference Include="..\GtMotive.Fleet.Infrastructure\GtMotive.Fleet.Infrastructure.csproj" />
    </ItemGroup>

    <ProjectExtensions>
        <VisualStudio>
            <UserProperties appsettings_1development_1json__JsonSchema="https://json.schemastore.org/appsettings" />
        </VisualStudio>
    </ProjectExtensions>


</Project>
